"""add_coupang_ad_report_table

Revision ID: 79c5bf56a7eb
Revises: c7d2e1f3a4b5
Create Date: 2026-05-18 18:58:28.775393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c5bf56a7eb'
down_revision: Union[str, None] = 'c7d2e1f3a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupang_ad_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('sell_type', sa.String(length=10), nullable=False),
    sa.Column('vendor_id', sa.String(length=20), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ad_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('sales_qty', sa.Integer(), nullable=False),
    sa.Column('conversion_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'sell_type', 'vendor_id', name='uq_coupang_ad_report')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupang_ad_report')
    # ### end Alembic commands ###
