"""add_refresh_token_expires_at_to_oauth_tokens

Revision ID: e8f0d3882c59
Revises: 1b60d8e50617
Create Date: 2026-04-02 07:53:28.953779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f0d3882c59'
down_revision: Union[str, None] = '1b60d8e50617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_tokens', 'refresh_token_expires_at')
    # ### end Alembic commands ###
